### ISSUE TITLE
Initial Setup

### ISSUE THREAD

**Issue by yhawamdeh** [yhawamdeh/taskinator#1]
## Requirements
* Create the task tracking HTML page that needs a:
   * Header
   * Main content area for the task list
   * Footer
* Use the style sheet provided
* Add functionality to the button to add tasks to the list

**Comment by ahmadjubair33** [comment]
Hi, @yhawamdeh I have raised a Pr for this issue please review it and merge it.Thank you

**Comment by yhawamdeh** [comment]
Finished this task
